spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  application:
    name: food-delivery marketplace

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Mirsaid15
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      
    mongodb:
      uri: mongodb://admin:Mirsaid15@localhost:27017/food_delivery?authSource=admin

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ha0gifBX5HlfIndkuD8ysLvB8QAVwBPKe9jMibjsB1o
  expiration: 360000
