spring:
  application:
    name: food-delivery-backend

  datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    analytics-enabled: true
  mongodb:
    uri: mongodb://admin:Mirsaid15@mongodb:27017/food_delivery?authSource=admin

server:
  port: 8080
